os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - SIMLIFE_TRAVIS=$HOME/generator-simlife/travis
    - SIMLIFE_SAMPLES=$SIMLIFE_TRAVIS/samples
    - SIMLIFE_SCRIPTS=$SIMLIFE_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

    # if SIMLIFE_DEPENDENCIES_BRANCH value is release, use the release from Maven
    - SIMLIFE_DEPENDENCIES_REPO=https://github.com/simlife/simlife-dependencies.git
    - SIMLIFE_DEPENDENCIES_BRANCH=release
    # if SIMLIFE_LIB_BRANCH value is release, use the release from Maven
    - SIMLIFE_LIB_REPO=https://github.com/simlife/simlife.git
    - SIMLIFE_LIB_BRANCH=release
    # if SIMLIFE_BRANCH value is release, use the release from NPM
    - SIMLIFE_REPO=https://github.com/simlife/generator-simlife.git
    - SIMLIFE_BRANCH=master

  matrix:
    - SIMLIFE=ngx-default PROFILE=prod PROTRACTOR=1
    - SIMLIFE=ngx-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    - SIMLIFE=ngx-gradle-fr PROFILE=prod PROTRACTOR=1
    - SIMLIFE=ngx-mariadb-oauth2-sass-infinispan PROTRACTOR=1
    - SIMLIFE=ngx-h2mem-social-ws-nol2
    - SIMLIFE=ngx-mongodb-kafka-cucumber
    - SIMLIFE=ngx-session-cassandra-fr
    - SIMLIFE=ngx-couchbase
    - SIMLIFE=ms-ngx-gateway-eureka
    - SIMLIFE=ms-ngx-gateway-consul
    - SIMLIFE=ms-ngx-gateway-uaa
    - SIMLIFE=ms-micro-eureka
    - SIMLIFE=ms-micro-consul
    - SIMLIFE=react-default
    - SIMLIFE=ng1-default

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn -v
  - yarn global add yo bower gulp-cli
install:
  - $TRAVIS_BUILD_DIR/travis/scripts/00-install-simlife.sh
  # generate project and entities
  - $SIMLIFE_SCRIPTS/01-generate-entities.sh
  - $SIMLIFE_SCRIPTS/02-generate-project.sh
script:
  - $SIMLIFE_SCRIPTS/03-docker-compose.sh
  - $SIMLIFE_SCRIPTS/04-tests.sh
  - $SIMLIFE_SCRIPTS/05-run.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
